* Pathfinding Commands

#+begin_src sh
clingo ../example.lp pathfinding-subnodes.lp show-path.lp -c h=11 0
clingo ../example.lp pathfinding-edge-functions.lp show-path.lp -c h=11 0
clingo ../example.lp pathfinding-hypergraph.lp show-path.lp -c h=11 0
#+end_src

* Drive Commands

#+begin_src sh
clingo ../example.lp pathfinding-subnodes.lp drive.lp -c h=11 0
clingo ../example.lp pathfinding-edge-functions.lp drive.lp -c h=11 0
clingo ../example.lp pathfinding-hypergraph.lp drive.lp -c h=11 0
#+end_src

To apply collision detection, just include =drive-collision.lp= in the above call to clingo.
r
* Calculating number of drives construtable from a given path

Take a path $p$ of length $n$. We consider drives with a maximal makespan of $m$ and assume $n \leq m$
We denote binomial coefficiants as $C(n,k)$.
The formula for the number of drives constructable from $p$ with max makespan $m$ is as follows:
$C(m,n)$.

In our encodings, we have $h+1=m$, where $h$ is the horizon. In =example.lp=, when $10 \leq h \leq 13$, the single path from the train's start to end node is of length $11$.
We can see that the encodings produce the correct results by observing the number of models and plugging in our formula.

=clingo ../example.lp pathfinding-subnodes.lp drive.lp -c h=11 0= -> $12 = C(12,11)$ models

=clingo ../example.lp pathfinding-subnodes.lp drive -c h=12 0= -> $78 = C(13,11)$ models

=clingo ../example.lp pathfinding-subnodes.lp drive -c h=13 0= -> $364 = C(14,11)$ models

Note that if we increate $h$ to $14$, an additional path is made possible - one containing repetitions. While repetitions are usually not allowed for path according to our definitions, for the purposes of caluclating drives they should also be considered. This can be toggled via the constant =allow_repetitions=.

Due to the additional path, for $h=14$ there will be one additional drive, so we get $1366 = C(15,11) + 1$  models.
In general then, given a flatland environment $E$ and a horizon $h$, the number of expected drives with length $\leq h+1$, is given by the formula below:

$|Drives(E,h)| = \sum_{p \in Paths(E,h)} C(h+1, len(p))$

Where $Paths(E,h)$ is the set of all paths in enviroment $E$ with $len(p) \leq h+1$.

** Proof sketch

To construct a drive from a path, we can add additional wait actions along the path, or we can delay the beginning of the drive. The sum of
the start delay and wait actions can be at most $m - n$, which we call our delay budget.

We can think of this problem then as a counting problem, where we need to put $m - n$ indistinguishable balls into $n + 1$ distinguishable
bins. The balls in this analogy are our delay budget, which we can allocate to any given cell in the path, excluding the goal cell, by
taking a wait action at that cell, thus accounting for $n-1$ bins. An additional bin is accounted for by the possibility of delaying our
start. Finally, the last bin is given by the fact that use of the delay budget is optional - we can think of elements of the delay budget we
don't use as being put in this last bin.

The [[https://en.wikipedia.org/wiki/Stars_and_bars_(combinatorics)][stars and bars theorem]] then gives us the formula for number of drives constructable from the given path as $C((n+1)+(m-n)-1,(n+1)-1)=C(m,n)$.
